name: Deploy Quartz to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for git info

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Update deployment timestamp
        run: |
          TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M UTC')
          sed -i "s/\*\*📅 Last Updated:\*\* .*/\*\*📅 Last Updated:\*\* $TIMESTAMP/" content/index.md
          echo "Updated timestamp to: $TIMESTAMP"

      - name: Build Quartz site
        run: npx quartz build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'deploy: Quartz site deployment from ${{ github.sha }}'

      - name: Notify Discord of successful deployment
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s' | head -c 100)
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)

          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"📚 Documentation Deployed\",
              \"description\": \"Archery Apprentice documentation has been updated and deployed.\",
              \"color\": 3447003,
              \"fields\": [
                {
                  \"name\": \"Commit\",
                  \"value\": \"\`$COMMIT_SHA_SHORT\` - $COMMIT_MESSAGE\",
                  \"inline\": false
                },
                {
                  \"name\": \"Author\",
                  \"value\": \"$COMMIT_AUTHOR\",
                  \"inline\": true
                },
                {
                  \"name\": \"Site\",
                  \"value\": \"[View Documentation](https://blamechris.github.io/archery-apprentice-docs/)\",
                  \"inline\": true
                }
              ],
              \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
            }]
          }" \
          "$DISCORD_WEBHOOK_URL"

      - name: Notify Discord of deployment failure
        if: failure()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMIT_SHA_SHORT=$(git rev-parse --short HEAD)

          curl -H "Content-Type: application/json" \
          -d "{
            \"embeds\": [{
              \"title\": \"❌ Documentation Deployment Failed\",
              \"description\": \"Failed to deploy documentation updates.\",
              \"color\": 15158332,
              \"fields\": [
                {
                  \"name\": \"Commit\",
                  \"value\": \"\`$COMMIT_SHA_SHORT\`\",
                  \"inline\": true
                },
                {
                  \"name\": \"Workflow\",
                  \"value\": \"[View Logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})\",
                  \"inline\": true
                }
              ],
              \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
            }]
          }" \
          "$DISCORD_WEBHOOK_URL"
